Update page aa1
aichner/Sonnenarm-Homepage pull request #14
Opened 2020-06-04 10:46 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently the page can not be deployed.
- Currently the code quality is not up to standards.

**What is the new behavior (if this is a feature change)?**
- The page can now be deployed.
- The code quality has been improved by applying prettier.

2020-06-04 15:04 UTC, LucaAllmaier commented on src/App.js
>   * Copyright © 2019 Werbeagentur Christian Aichner
missing -2020

2020-06-04 15:09 UTC, LucaAllmaier commented on src/components/molecules/Navbar/index.jsx
> +    const { collapseID } = this.state;
add new line

2020-06-04 15:14 UTC, LucaAllmaier requested changes
Looks good after some changes.

2020-06-08 07:41 UTC, LucaAllmaier commented on src/components/molecules/Navbar/index.jsx
> +
indentation bug again?

2020-06-08 07:44 UTC, LucaAllmaier approved these changes
Looks good.

2020-06-08 07:59 UTC, Aichnerc commented on src/components/molecules/Navbar/index.jsx
> +
Thanks for pointing that out.

2020-06-08 08:00 UTC, merged